name: Komunikacja Techniczna, Akademia Finansów i Biznesu Vistula
title: Sending newspaper to print because why not
description: Let's learn more about printing and all that jazz
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: dark

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/Monika-Skoneczna"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). The content is based on <a href=\"https://github.com/flicstar/DITA-Mini-Manual\">Felicity Brand's example DITA project.</a>"